### ISSUE TITLE
commenting?

### ISSUE THREAD

**Issue by Sillerd** [alexandersjn/btc_e_assist_api#1]
I'm trying to look at what the code means because im having issues in calling functions out of order and most of the functions don't have any sort of documenation.

**Comment by alexandersjn** [comment]
Ooops :) I can answer to you right now.

**Comment by Sillerd** [comment]
how do i get account balance for both usd and btc, as well as current bid and ask, then update(is that tradeapi.ticker.runmethod)? thank you.

**Comment by Sillerd** [comment]
actually on second thought seems to be self evident figured it all out. sorry for bugging you :)

**Comment by alexandersjn** [comment]
Get running orders:
String KEY = "98Q8VR12-9XZLORFG-7CC4XJUW-NB87YA0G-3FZ93GFR";
        String SECRET = "a49e9fe8700a94e1068ddb2c00f63ff54c4bdb32e3172eb3fb34c48f53f2325e";
        TradeApi tradeApi = new TradeApi(KEY, SECRET);
        tradeApi.activeOrders.runMethod();
        while (tradeApi.activeOrders.hasNext()) {
            tradeApi.activeOrders.switchNext();
        }

**Comment by alexandersjn** [comment]
String KEY = "aabbcc...";
        String SECRET = "aaffbb...";
        TradeApi tradeApi = new TradeApi(KEY, SECRET);
        tradeApi.activeOrders.runMethod();
        while (tradeApi.activeOrders.hasNext()) {
            tradeApi.activeOrders.switchNext();                       
            System.out.println(tradeApi.activeOrders.getCurrentRate());
        }

Console output will contain your orders prices. You can get more info about method "activeOrders" here https://btc-e.com/tapi/docs#ActiveOrders

**Comment by Sillerd** [comment]
thank you :+1:
