### ISSUE TITLE
Attempting to use tryMaximumBuy() and tryMaximumSell()

### ISSUE THREAD

**Issue by Phalanxguard** [alexandersjn/btc_e_assist_api#2]
I have to sympathize with the last issue as well, I find using the code without any javadoc quite difficult. Anyhow I've been attempting to use the tryMaximumBuy() and tryMaximumSell() methods, I've input the pair as "btc_usd" and the long parameter as unix time. I've also put my key and secret key into the constructor arguments of the instance of tradeApi that I am using. The method throws "Multiple Failure". Any idea of what I'm doing wrong or (even better) any chance of an example?

Cheers

**Comment by alexandersjn** [comment]
Hi!
I'm sorry for my code, today I see that it's really strange :)
Some javadoc you can find in the /doc directory (index.html is the start page).

About your issue: you do it RIGHT, except long parameter as unix time. In method `double tryMaximumBuy(String pairName, long reuseAgeMillis)` as you can see in javadoc (yes, this method has javadoc) second parameter is a limit for data reusing. Just set it to 10 000 for example (10 seconds) and all will work fine :)

```
String KEY = "AAA-bbb-123";
String SECRET = "123abcd";
TradeApi tradeApi = new TradeApi(KEY, SECRET);
double btc_usd = tradeApi.tryMaximumBuy("btc_usd", 10 * 1000);
System.out.println(btc_usd);
```
